server:
  port: 8080

spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local