server:
  port: 10001
  shutdown: graceful

spring:
  profiles:
    active: local
  application:
    name: usermodule

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: usermodule
    description: usermodule server component
    version: 0.0.1-SNAPSHOT

custom:
  id: 4