server:
  port: 10001

spring:
  profiles:
    active: local
  application:
    name: usermodule

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: usermodule
    description: user management module for customer and administrator
    version: 0.0.1SNAPTHOT