apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: owen8527/user:latest
          ports:
            - containerPort: 10001
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: AUTHORIZATION_URL
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: AUTHORIZATION_URL
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001