
server:
  port: 8999

spring:
  application:
    name: eurekaserver
  profiles:
    active: "@environment@"
  devtools:
    restart:
      enabled: true
      additional-paths: target\classes\config\application.yml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: ${spring.application.name}



management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: eurekaserver
    description: eureka server component
    version: 0.0.1-SNAPSHOT


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
