server:
  port: 8999
  shutdown: graceful

spring:
  application:
    name: eurekaserver
  profiles:
    active: "@environment@"
  devtools:
    restart:
      enabled: true
      additional-paths: target\classes\config\application.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: eurekaserver
    description: eureka server component
    version: 0.0.1-SNAPSHOT


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
