
server:
  port: 8999

spring:
  application:
    name: eurekaserver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"

