server:
  port: 9000

spring:
  application:
    name: authserver
  profiles:
    active: '@environment@'
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"