server:
  port: 9000

authorization:
  url: http://auth-server:${server.port}

spring:
  application:
    name: authserver
  profiles:
    active: '@environment@'
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: authserver
    description: auther server component
    version: 0.0.1-SNAPSHOT
