server:
  port: 9000
  shutdown: graceful

spring:
  application:
    name: authserver
  profiles:
    active: '@environment@'
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: authserver
    description: auther server component
    version: 0.0.1-SNAPSHOT

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

