server:
  port: 80

spring:
  profiles:
    active: '@environment@'
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-management-client
          predicates:
            - Path=/user/sayHello
            - Method=GET,POST
        - id: photo
          uri: lb://photo-sharing-client
          predicates:
            - Path=/photo/sayHello
            - Method=GET,POST
  application:
    name: gateway-client

