server:
  port: 80
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  profiles:
    active: '@environment@'
  cloud:
    config:
      enabled: true
  #route forwarding
    gateway:
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: false #options request is intercepted
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: photo-service
          uri: lb://photo
          predicates:
            - Path=/photo/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: openapi
#          TODO fixed configuration is not suitable
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger/api-docs/**
          filters:
#            - todo check this maybe can solve the user leading path issue
            - RewritePath=/swagger/api-docs/(?<path>.*), /$\{path}/swagger/api-docs
  session:
    redis:
      flush-mode: IMMEDIATE # session refresh mode
      namespace: gateway:session # namespace for keys used to store sessions

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: gateway
    description: gateway server component
    version: 0.0.1-SNAPSHOT

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /swagger/api-docs/user
      - name: photo
        url: /swagger/api-docs/photo