logging:
  level:
    root: info
    org.springframework.security: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8000



## this is the first version

## this is the second verison
