server:
  port: 80
  servlet:
    session:
      cookie:
        name: GATEWAY
  shutdown: graceful

spring:
  application:
    name: gateway
  profiles:
    active: '@environment@'
  cloud:
    config:
      enabled: true
  #route forwarding
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: photo
          uri: lb://photo
          predicates:
            - Path=/photo/**
          filters:
            - TokenRelay
            - StripPrefix=1
  session:
    redis:
      flush-mode: on_save # session refresh mode
      namespace: gateway:session # namespace for keys used to store sessions

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: gateway
    description: gateway server component
    version: 0.0.1-SNAPSHOT

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
