server:
  port: 80

spring:
  profiles:
    active: '@environment@'
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://127.0.0.1:9003
          predicates:
            - Path=/user/sayHello
            - Method=GET,POST
        - id: photo
          uri: http://127.0.0.1:9004
          predicates:
            - Path=/photo/sayHello
            - Method=GET,POST


