server:
  port: 80

spring:
  profiles:
    active: '@environment@'
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-management-client
          predicates:
            - Path=/user/*
        - id: photo
          uri: lb://photo-sharing-client
          predicates:
            - Path=/photo/*
        - id: oauth
          uri: lb://authenrization-client
          predicates:
            - Path=/oauth/*
  application:
    name: gateway-client

