apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: owen8527/configserver:latest
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: finalproject-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      # this port is the one expose to outer
      port: 9001
      # this port value should be equal to container port
      targetPort: 9001
