#logging:
#  level:
#    root: info
#    org.springframework.security: trace
#
#spring:
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://auth-server:9000
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8999/eureka