server:
  port: 0

spring:
  profiles:
    active: '@environment@'
  application:
    name: user-management-client

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}}