# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: authserver-deployment
deploymentLabel: authserver
appName: authserver

replicaCount: 1

image:
  repository: owen8527/authserver
  tag: latest

containerPort: 9000

service:
  type: LoadBalancer
  port: 9000
  targetPort: 9000

profile_enabled: true
zipkin_enabled: true
eureka_enabled: true
auth_enabled: true
redis_enabled: false
datasource_enabled: true