# fine_grained_token: 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

server:
  port: 0

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://zewenw: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@github.com/zewenw/final_project_config
          clone-on-start: true
          default-label: master


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8999/eureka

