server:
  port: 9001
  shutdown: graceful

spring:
  profiles:
    active: git
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zewenw/final_project_config.git
          clone-on-start: true
          default-label: master
  devtools:
    restart:
      enabled: true
      additional-paths: target\classes\config\application.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: configserver
    description: config server component
    version: 0.0.1-SNAPSHOT


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"