spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans


eureka:
  instance:
    prefer-ip-address: true
  #    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
  client:
    service-url:
      defaultZone: http://eurekaserver-service:8999/eureka
