spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OAuth
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1

logging:
  level:
    root: info
    org.springframework.security: trace