server:
  port: 12306


spring:
  application:
    name: demomodule
  profiles:
    active: @environment@

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
  client:
    service-url:
      defaultZone: http://eurekaserver:8999/eureka/
