server:
  port: 10002
  shutdown: graceful

spring:
  profiles:
    active: local
  application:
    name: photo

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: photo
    description: photo server component
    version: 0.0.1-SNAPSHOT

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
    instances:
      retryForUserApp:
        baseConfig: default

  circuitbreaker:
    instances:
# this should be correspond to the specific service which is invoked by this service
      detailsForUserApp:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10