server:
  port: 8080

spring:
  profiles:
    active: '@environment@'
  security:
    oauth2:
      client:
        registration:
          final_project:
            client-id: client
            client-secret: secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/final_project
        provider:
          final_project:
            issuer-uri: http://auth-server:8000

