server:
  port: 9002

spring:
  profiles:
    active: '@environment@'
  security:
    oauth2:
      client:
        registration:
          final_project:
            clientId: client
            clientSecret: secret
            scope: openid
            authorizationGrantType: authorization_code
            redirectUri: http://127.0.0.1:9002/login/oauth2/code/final_project
        provider:
          final_project:
            issuer-uri: http://auth-server:9000
#            userInfoUri: http://auth-server:9000/userinfo
#            tokenUri: http://auth-server:9000/oauth2/token
#            authorizationUri: http://auth-server:9000/oauth2/authorize
#            jwkSetUri: http://auth-server:9000/oauth2/jwks

