# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: photo-deployment
deploymentLabel: photo
serviceName: photo-service
appName: photo

replicaCount: 1

image:
  repository: owen8527/photo
  tag: latest

containerPort: 10002

service:
  type: LoadBalancer
  port: 10002
  targetPort: 10002

profile_enabled: true
zipkin_enabled: true
eureka_enabled: true
auth_enabled: true
redis_enabled: true
datasource_enabled: false