server:
  port: 0

spring:
  profiles:
    active: '@environment@'
  application:
    name: photo-sharing-client
  cloud:
    config:
      enabled: false


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}}