# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: user-deployment
deploymentLabel: user
appName: user

replicaCount: 1

image:
  repository: owen8527/user
  tag: latest

containerPort: 10001

service:
  type: LoadBalancer
  port: 10001
  targetPort: 10001

profile_enabled: true
zipkin_enabled: true
eureka_enabled: true
auth_enabled: true
redis_enabled: false
datasource_enabled: true